[workspace]
members = [
    "windows-kernel-alloc",
    "windows-kernel-macros",
    "windows-kernel-string",
    "windows-kernel-sys",
    "windows-rust-minifilter",
    "windows-kernel-mutex",
]
exclude = [
    "windows-rust-application"
]
