[env]
DRIVER_NAME = "driver"
DDK_PLATFORM = "x64"
VC_BUILD_DIR = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"

[tasks.build-driver]
script = '''
cargo b %BUILD_FLAGS%
'''

[env.development]
TARGET_PATH = "target/x86_64-pc-windows-msvc/debug"

[env.production]
TARGET_PATH = "target/x86_64-pc-windows-msvc/release"
BUILD_FLAGS = "--release"

[tasks.rename]
script = '''
cd %TARGET_PATH%
rename %DRIVER_NAME%.dll %DRIVER_NAME%.sys
'''

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = '''
call "%VC_BUILD_DIR%"
if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )
signtool sign /fd SHA256 /a /v /s PrivateCertStore /n DriverCertificate /t http://timestamp.digicert.com %TARGET_PATH%/%DRIVER_NAME%.sys
'''

[tasks.all]
dependencies = ["build-driver", "rename", "sign"]
